name: Publish on Netlify and Supabase

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  deploy-supabase:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: rrjgbneefiwoqvsjwzrz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID --workdir packages/database
